# Generated by Django 6.0 on 2025-12-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('CONFIRMED', 'Confirmed'), ('Delivered', 'DELIVERED')], default='PENDING', max_length=20),
        ),
    ]
