# Generated by Django 6.0 on 2025-12-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_address_order_city_order_phone_order_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('Confirmed', 'CONFIRMED'), ('Delivered', 'DELIVERED')], default='PENDING', max_length=20),
        ),
    ]
